# Generated by Django 5.2.14 on 2026-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
