# Generated by Django 5.2.14 on 2026-05-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_stripe_checkout_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
