# Generated by Django 4.2.11 on 2026-04-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='temp_username', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
